name: WhatsApp Schedule

on:
  push:
    branches:
      - new   # your default branch
  workflow_dispatch:

jobs:
  send_messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "FIREBASE_CRED_PATH=ayushvi-whatsapp-firebase-9.json" >> $GITHUB_ENV

      - name: Run WhatsApp message script
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: python whats_fire.py
